### PR TITLE
Fix FAWE logging on newer builds

### LINKED ISSUE #496: WorldEdit (FAWE) support doesn't work
WorldEdit (FAWE) support doesn't work in the latest version v22.2 with latest FAWE build 646 in 1.20.4

Video: https://imgur.com/p6Uw5Vh

### PR DESCRIPTION
**Pull request by Telesphoreo**
Jar download: https://s3.telesphoreo.me/coreprotect/CoreProtect-fork-22.2-v22.2-23-g162c4a8.dirty.jar

Fixes #496

### CODE REVIEW

**Comment by Intelli** [comment]
Just to confirm, are the maven/gradle build file changes necessary?

It doesn't appear that you're making any FAWE dependant API calls in your code changes.

**Comment by VideoGameSmash12** [comment]
FAWE is like a double-edged sword. Sure, it doesn't crash your server when you do a gigantic edit and it has a bunch of neat features, but you will randomly get breaking changes like what happened here.

**Comment by Telesphoreo** [comment]
Unfortunately, I take it back. CoreProtect doesn't compile with stock WE with these changes.

**Comment by Telesphoreo** [comment]
I have removed the enable-awe toggle entirely. AWE is dead and it appears that FAWE registers the same way as WorldEdit. The worldedit toggle being set to true or false will work both for FAWE or regular WE, so I think it should be removed to reduce confusion. Let me know if you want any of that back though

**Pull request merged**
