### PR TITLE
Feature/networking client queries

### PR DESCRIPTION
**Pull request by vacla**
Follow up of https://github.com/PlayPro/CoreProtect/pull/211

### CODE REVIEW

**Comment by vacla** [comment]
Bumping as this can only go in a major release apparently

**Comment by vacla** [comment]
Would it be possible to answer on my questions that i had in #development channel in Discord since otherwise this pull go nowhere but it will really help me maintain compat with coreprotect, I currently use this already for Ledger (Fabric variant) and wanted to implement it for CoreProtect.

**Comment by Intelli** [comment]
PR needs to be simplified for review. No chat methods should be modified, no unnecessary functionality should be included (something like a networking command should be it’s own standalone PR for acceptance or rejection).

**Comment by vacla** [comment]
@Intelli why are these chat method not allowed to be modified since i only modified the ones that really give info like a warning or a critical message so i can show them in an UI on the client, all others should still be using their original method right now, in a previous version there were lots more.

**Comment by Intelli** [comment]
Same reason I stated in the last PR: https://github.com/PlayPro/CoreProtect/pull/211#issuecomment-1347423510

This needs minimal modification/interaction with existing code, as it’s not something I’ll be testing or maintaining myself between versions.

Hijacking the chat methods is a messy solution which degrades the quality of the recently rewritten internal chat/language system.

I’m not sold on this PR, as it’s not really providing any new functionality that isn’t already possible, and is creating extra work in terms of maintainability. If this PR was much simpler, I’d be less concerned, but there seems to be a bunch of unnecessary complexity here. E.g. still modifying the language file, adding a new command, modifying existing methods, etc.

**Pull request closed without merging**
